import Head from 'next/head';
import Image from 'next/image';
import BenefitList from '../src/components/Benefits/BenefitList';
import CardInfo from '../src/components/Cards/CardInfo';
import Tecnologies from '../src/components/Cards/Tecnologies';
import ContainerSection from '../src/components/Containers/ContainerSection';
import ContainerSectionDev from '../src/components/Containers/ContainerSectionDev';
import Cover from '../src/components/Containers/Cover';
import ContactForm from '../src/components/Forms/ContactForm';
import Layout from '../src/components/Layout/Layout';
import ProjectList from '../src/components/Projects/ProjectList';
import ServiceList from '../src/components/Services/ServiceList';
import { coverData } from '../src/data/cover.data';


export default function Home() {



  return (
    <Layout>
      <Head>
        <title>MHCode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className='background__stars'></div> */}

      <main className='container__general'>
        <Cover
          title={ coverData.title }
          text={ coverData.text }
        />

        <ContainerSectionDev subtitle='Acerca de mí'>
          <CardInfo />
        </ContainerSectionDev>

        <ContainerSection identifier='tecnologies' subtitle='Algunas tecnologías que uso...'>
          <Tecnologies />
        </ContainerSection>

        {/* <div className='block__section block__section-1'>
          
        </div> */}

        <ContainerSection identifier='services' subtitle='Servicios'>
          <ServiceList />
        </ContainerSection>

        <ContainerSection identifier='benefits' subtitle='Beneficios'>
          <BenefitList />
        </ContainerSection>

        <div className='block__section block__section-2'>
         
        </div>

        {/* <div className='block__section block__section-3'>
          <ContainerSection subtitle='Mis proyectos'>
            <ProjectList />
          </ContainerSection>
        </div> */}

        <div className='block__section block__section-4'>
          <ContainerSection  identifier='contact' subtitle='Tu proyecto está casi listo!'>
            <ContactForm />
          </ContainerSection>
        </div>
      </main>
    </Layout>
  )
}
